FROM php:5.6-fpm

MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>

ADD ./laravel.ini /usr/local/etc/php/conf.d
ADD ./laravel.pool.conf /usr/local/etc/php-fpm.d/

RUN apt-get update && apt-get install -y \
    libpq-dev \
    libmemcached-dev \
    curl \
    libpng12-dev \
    libldap2-dev \
    libfreetype6-dev \
    libaio-dev \
    wget \
    unzip \
    --no-install-recommends \
    && rm -r /var/lib/apt/lists/*


# Install Oracle Instantclient
RUN mkdir /opt/oracle \
    && cd /opt/oracle \
    && wget https://s3.amazonaws.com/merofile/instantclient-basic-linux.x64-12.1.0.2.0.zip \
    && wget https://s3.amazonaws.com/merofile/instantclient-sdk-linux.x64-12.1.0.2.0.zip \
    && unzip /opt/oracle/instantclient-basic-linux.x64-12.1.0.2.0.zip -d /opt/oracle \
    && unzip /opt/oracle/instantclient-sdk-linux.x64-12.1.0.2.0.zip -d /opt/oracle \
    && ln -s /opt/oracle/instantclient_12_1/libclntsh.so.12.1 /opt/oracle/instantclient_12_1/libclntsh.so \
    && ln -s /opt/oracle/instantclient_12_1/libclntshcore.so.12.1 /opt/oracle/instantclient_12_1/libclntshcore.so \
    && ln -s /opt/oracle/instantclient_12_1/libocci.so.12.1 /opt/oracle/instantclient_12_1/libocci.so \
    && rm -rf /opt/oracle/*.zip


# Install OCI 8
RUN echo 'instantclient,/opt/oracle/instantclient_12_1/' | pecl install oci8-1.4.10
RUN docker-php-ext-configure pdo_oci \
    --with-pdo-oci=instantclient,/opt/oracle/instantclient_12_1,12.1 


# Configure ldap library
RUN docker-php-ext-configure ldap \
    --with-libdir=lib/x86_64-linux-gnu/


# configure gd library
RUN docker-php-ext-configure gd \
    --enable-gd-native-ttf \
    --with-freetype-dir=/usr/include/freetype2

# Install extensions using the helper script provided by the base image
RUN docker-php-ext-install \
    pdo_mysql \
    pdo_pgsql \
    ldap \
    gd \
    pdo_oci


# Install xdebug
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

# Enable oci8 extesion
RUN docker-php-ext-enable oci8 

RUN usermod -u 1000 www-data

WORKDIR /var/www/laravel

CMD ["php-fpm"]

EXPOSE 9000
